Repository corentingoo/Learning_project_group_2, pull requests merged in 2022-12, with the labels that each got.

#64 Feature 47 formation date
  src/main/java/be/ifosup/learning/formations/entities/Formation.java
  src/main/java/be/ifosup/learning/formations/in/FormationIn.java
  src/main/java/be/ifosup/learning/formations/out/FormationOut.java
  src/main/java/be/ifosup/learning/formations/service/FormationServiceImpl.java
  src/main/java/be/ifosup/learning/users/entities/User.java
  src/main/java/be/ifosup/learning/users/repositories/UserRepository.java
  src/main/java/be/ifosup/learning/webservice/controller/admin/FormationController.java
  src/main/resources/db/migration/V1_2_0__formation_date_fk.sql
  src/main/resources/templates/admin/formation/create.html
  src/main/resources/templates/admin/formation/index.html
  src/main/resources/templates/admin/formation/update.html
Labels: feature

#67 Documentation 62 Epic lien user/formation
  Docs/Epic_lien_user_formation/analyse fonctionnelle.md
  Docs/Epic_lien_user_formation/analyse technique.md
  Docs/Epic_lien_user_formation/stories.md
Labels: documentation

#73 Profile
  src/main/java/be/ifosup/learning/controller/ProfileController.java
  src/main/java/be/ifosup/learning/controller/admin/UserController.java
  src/main/java/be/ifosup/learning/email/service/EmailServiceImpl.java
  src/main/java/be/ifosup/learning/users/service/UserServiceImpl.java
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/fragments/sidebarteacher.html
  src/main/resources/templates/public/profile.html
Labels: feature, seen by corentin, seen by julien

#60 Documentation 59 frontend connexion
  Docs/EPIC_frontend_page_connexion/Analyse FrontEnd Page Connexion 59 _analyse fonct.md
  Docs/EPIC_frontend_page_connexion/Analyse FrontEnd Page Connexion 59 _analyse tech.md
  Docs/EPIC_frontend_page_connexion/Analyse FrontEnd Page Connexion 59 _mockup.md
  Docs/EPIC_frontend_page_connexion/Analyse FrontEnd Page Connexion 59 _stories.md
  Docs/EPIC_frontend_page_connexion/LProject _Page Connexion _UX UI _Fin.jpg
Labels: documentation

#31 Documentation-26-analyse-update-formation
  Docs/EPIC_update_formation/Analyse update formation 26 _analyse fonct.md
  Docs/EPIC_update_formation/Analyse update formation 26 _analyse tech.md
  Docs/EPIC_update_formation/Analyse update formation 26 _mockup.md
  Docs/EPIC_update_formation/Analyse update formation 26 _modele de donnees.md
  Docs/EPIC_update_formation/Analyse update formation 26 _stories.md
  Docs/EPIC_update_formation/LP _Learning DB _schema DB _table formation _Fin.jpg
  Docs/EPIC_update_formation/LProject _Formation _Logique _update _Fin.jpg
  Docs/EPIC_update_formation/LProject _Formation _MindMap _Code HTTP _Fin.jpg
  Docs/EPIC_update_formation/LProject _Formation _MindMap _Path du update _Fin.jpg
  Docs/EPIC_update_formation/LProject _Formation _UX UI _update formation _Fin.jpg
  Docs/EPIC_update_formation/LProject _Formation _UX UI _update formation _Mockup _Apres _Fin.jpg
  Docs/EPIC_update_formation/LProject _Formation _UX UI _update formation _Mockup _Avant _Fin.jpg
  Docs/EPIC_update_formation/LProject _Formation _UX UI _update formation _Mockup _Pendant _Fin.jpg
Labels: documentation, need to review, seen by corentin, seen by julien

#29 Documentation-27-analyse-delete-formation
  Docs/EPIC_delete_formation/Analyse delete formation 27 _analyse fonct.md
  Docs/EPIC_delete_formation/Analyse delete formation 27 _analyse tech.md
  Docs/EPIC_delete_formation/Analyse delete formation 27 _mockup.md
  Docs/EPIC_delete_formation/Analyse delete formation 27 _modele de donnees.md
  Docs/EPIC_delete_formation/Analyse delete formation 27 _stories.md
  Docs/EPIC_delete_formation/LP _Learning DB _schema DB _table formation _Fin.jpg
  Docs/EPIC_delete_formation/LProject _Formation _Logique _delete Fin.jpg
  Docs/EPIC_delete_formation/LProject _Formation _MindMap _Code HTTP _Fin.jpg
  Docs/EPIC_delete_formation/LProject _Formation _MindMap _Path du delete _Fin.jpg
  Docs/EPIC_delete_formation/LProject _Formation _UX UI _delete formation _Fin.jpg
  Docs/EPIC_delete_formation/LProject _Formation _UX UI _delete formation _Mockup _Apres.jpg
  Docs/EPIC_delete_formation/LProject _Formation _UX UI _delete formation _Mockup _Avant.jpg
Labels: documentation, need to review

#30 Documentation-28-analyse-read-formation
  Docs/EPIC_read_formation/Analyse read formation 28 _analyse fonct.md
  Docs/EPIC_read_formation/Analyse read formation 28 _analyse tech.md
  Docs/EPIC_read_formation/Analyse read formation 28 _mockup.md
  Docs/EPIC_read_formation/Analyse read formation 28 _modele de donnees.md
  Docs/EPIC_read_formation/Analyse read formation 28 _stories.md
  Docs/EPIC_read_formation/LP _Learning DB _schema DB _table formation _Fin.jpg
  Docs/EPIC_read_formation/LProject _Formation _Logique _read _Fin.jpg
  Docs/EPIC_read_formation/LProject _Formation _MindMap _Code HTTP _Fin.jpg
  Docs/EPIC_read_formation/LProject _Formation _MindMap _Path du read _Fin.jpg
  Docs/EPIC_read_formation/LProject _Formation _UX UI _read formation _Fin.jpg
  Docs/EPIC_read_formation/LProject _Formation _UX UI _read formation _Mockup _Fin.jpg
Labels: documentation, need to review

#76 Feature Type
  src/main/java/be/ifosup/learning/controller/admin/TypeController.java
  src/main/java/be/ifosup/learning/formations/service/FormationService.java
  src/main/java/be/ifosup/learning/formations/service/FormationServiceImpl.java
  src/main/java/be/ifosup/learning/types/entities/Type.java
  src/main/java/be/ifosup/learning/types/in/TypeIn.java
  src/main/java/be/ifosup/learning/types/out/TypeOut.java
  src/main/java/be/ifosup/learning/types/repositories/TypeRepository.java
  src/main/java/be/ifosup/learning/types/service/TypeService.java
  src/main/java/be/ifosup/learning/types/service/TypeServiceImpl.java
  src/main/resources/db/migration/V1_3_0__type_init.sql
  src/main/resources/templates/admin/formation/create.html
  src/main/resources/templates/admin/formation/update.html
  src/main/resources/templates/admin/type/create.html
  src/main/resources/templates/admin/type/index.html
  src/main/resources/templates/admin/type/update.html
  src/main/resources/templates/fragments/sidebaradmin.html
Labels: feature

#75 Inscription Student
  src/main/java/be/ifosup/learning/controller/admin/FormationController.java
  src/main/java/be/ifosup/learning/controller/admin/InscriptionController.java
  src/main/java/be/ifosup/learning/controller/student/InscriptionFormationStudentController.java
  src/main/java/be/ifosup/learning/controller/student/InscriptionStudentController.java
  src/main/java/be/ifosup/learning/inscriptions/out/InscriptionOut.java
  src/main/java/be/ifosup/learning/inscriptions/repositories/InscriptionRepository.java
  src/main/java/be/ifosup/learning/inscriptions/service/InscriptionService.java
  src/main/java/be/ifosup/learning/inscriptions/service/InscriptionServiceImpl.java
  src/main/resources/templates/fragments/sidebarstudent.html
  src/main/resources/templates/student/formation/create.html
  src/main/resources/templates/student/formation/index.html
  src/main/resources/templates/student/formation/inscription.html
  src/main/resources/templates/student/inscription/create.html
  src/main/resources/templates/student/inscription/formation.html
  src/main/resources/templates/student/inscription/index.html
  src/main/resources/templates/student/inscription/update.html
Labels: bug, feature

#77 Readme
  Docs/Epic PSW reset/analyse fonctionnelle.md
  Docs/Epic PSW reset/analyse technique.md
  Docs/Epic PSW reset/stories.md
  README.md
Labels: documentation

#80 Update InscriptionServiceImpl.java
  src/main/java/be/ifosup/learning/inscriptions/service/InscriptionServiceImpl.java
Labels: bug
