Repository corentingoo/Learning_project_group_2, pull requests merged in 2022-11, with the labels that each got.

#22 documentation-13-creation user
  Docs/EPIC_create_user/analyse fonctionnelle.md
  Docs/EPIC_create_user/analyse technique.md
  Docs/EPIC_create_user/schéma create user.JPG
  Docs/EPIC_create_user/stories.md
Labels: documentation, need to review, seen by corentin, seen by lydia

#19 Documentation-11-analyse-teacher-role
  Docs/EPIC_teacher_role/analyse fonctionnelle
  Docs/EPIC_teacher_role/analyse technique
  Docs/EPIC_teacher_role/stories
Labels: documentation, need to review, seen by julien

#39 Feature-38-ajout-des-roles-teacher-et-student-remplacement-user
  src/main/java/be/ifosup/learning/config/CustomAuthentificationSuccessHandler.java
  src/main/java/be/ifosup/learning/config/WebSecurityConfig.java
  src/main/java/be/ifosup/learning/constants/RoleEnum.java
  src/main/java/be/ifosup/learning/webservice/controller/student/StudentController.java
  src/main/java/be/ifosup/learning/webservice/controller/teacher/TeacherController.java
  src/main/java/db/migration/V1_0_2__AddUsers.java
  src/main/resources/templates/student/index.html
  src/main/resources/templates/teacher/index.html
Labels: feature, need to review, seen by corentin, seen by lydia

#20 documentation-17-analyse-de-la-recuperation-de-mot-de-passe
  Docs/Epic PSW reset/analyse fonctionnelle.md
  Docs/Epic PSW reset/analyse technique.md
  Docs/Epic PSW reset/stories.md
Labels: documentation, need to review, seen by corentin, seen by julien

#41 Feature 16 create formation
  src/main/java/be/ifosup/learning/formations/entities/Formation.java
  src/main/java/be/ifosup/learning/formations/repositories/FormationRepository.java
  src/main/java/be/ifosup/learning/formations/service/FormationService.java
  src/main/java/be/ifosup/learning/webservice/controller/formation/FormationController.java
  src/main/java/db/migration/V1_1_1__AddFormations.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1_1_0__formation_init.sql
  src/main/resources/templates/formations/index.html
Labels: feature

#21 documentation-14-analyse-create-formation
  Docs/EPIC_create_formation/Analyse creation formation 14 _analyse fonct _V2.md
  Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech V2.md
  Docs/EPIC_create_formation/Analyse creation formation 14 _mockup.md
  Docs/EPIC_create_formation/Analyse creation formation 14 _modele de donnees V2.md
  Docs/EPIC_create_formation/Analyse creation formation 14 _stories V2.md
  Docs/EPIC_create_formation/LP _Learning DB _schema DB _table formation _Fin.jpg
  Docs/EPIC_create_formation/LProject _Formation _Apres _Fin.jpg
  Docs/EPIC_create_formation/LProject _Formation _Avant _Fin.jpg
  Docs/EPIC_create_formation/LProject _Formation _Logique _create _Fin.jpg
  Docs/EPIC_create_formation/LProject _Formation _MindMap _Code HTTP _Fin.jpg
  Docs/EPIC_create_formation/LProject _Formation _MindMap _Path _Fin.jpg
  Docs/EPIC_create_formation/LProject _Formation _Pendant _Fin.jpg
  Docs/EPIC_create_formation/LProject _Formation _UX UI _Fin.jpg
  README.md
Labels: documentation, need to review, seen by corentin, seen by julien

#34 Documentation-18-frontend-page-accueil
  src/Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _analyse fonct.md
  src/Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _analyse tech.md
  src/Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _mockup.md
  src/Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _stories.md
  src/Docs/EPIC_frontend_page_accueil/LProject _Page Accueil _UX UI Fin.jpg
Labels: documentation, need to review, seen by corentin, seen by lydia, seen by julien

#45 Feature crud formation
  src/main/java/be/ifosup/learning/config/WebSecurityConfig.java
  src/main/java/be/ifosup/learning/formations/entities/Formation.java
  src/main/java/be/ifosup/learning/formations/in/CreateFormationIn.java
  src/main/java/be/ifosup/learning/formations/out/FormationOut.java
  src/main/java/be/ifosup/learning/formations/service/FormationService.java
  src/main/java/be/ifosup/learning/formations/service/FormationServiceImpl.java
  src/main/java/be/ifosup/learning/webservice/controller/admin/FormationController.java
  src/main/java/be/ifosup/learning/webservice/controller/formation/FormationController.java
  src/main/java/be/ifosup/learning/webservice/controller/formation/FormationWSController.java
  src/main/resources/templates/admin/formation/create.html
  src/main/resources/templates/admin/formation/index.html
  src/main/resources/templates/admin/formation/update.html
  src/main/resources/templates/admin/index.html
  src/main/resources/templates/formations/index.html
Labels: feature, seen by corentin, seen by julien

#50 Fix 49 update formation
  src/main/java/be/ifosup/learning/formations/in/FormationIn.java
  src/main/java/be/ifosup/learning/formations/service/FormationService.java
  src/main/java/be/ifosup/learning/formations/service/FormationServiceImpl.java
  src/main/java/be/ifosup/learning/webservice/controller/admin/FormationController.java
  src/main/java/be/ifosup/learning/webservice/controller/formation/FormationWSController.java
  src/main/resources/templates/admin/formation/update.html
Labels: bug

#55 correction création de table en SQL
  src/main/resources/db/migration/V1_0_0__init.sql
  src/main/resources/db/migration/V1_1_0__formation_init.sql
Labels: enhancement, need to review

#61 Deplacement de Doc
  Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _analyse fonct.md
  Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _analyse tech.md
  Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _mockup.md
  Docs/EPIC_frontend_page_accueil/Analyse FrontEnd Page Accueil 18 _stories.md
  Docs/EPIC_frontend_page_accueil/LProject _Page Accueil _UX UI Fin.jpg
Labels: documentation

#58 Feature 42 frontend accueil
  src/main/java/be/ifosup/learning/webservice/controller/LoginController.java
  src/main/resources/static/css/style.css
  src/main/resources/static/img/LProject_Accueil_Footer_Fin.png
  src/main/resources/static/img/LProject_Accueil_Pexels_Fin.jpg
  src/main/resources/static/img/LProject_Logo_Final.png
  src/main/resources/static/img/favicon.png
  src/main/resources/static/img/home.svg
  src/main/resources/static/img/right-to-bracket-solid.svg
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
Labels: feature
